language: java

sudo: false

dist: trusty

cache:
 directories:
   - $HOME/.m2

before_install:
  - unset _JAVA_OPTIONS
  - rm ~/.m2/settings.xml
  - export MAVEN_SKIP_RC=true
  - export MAVEN_OPTS="-Xmn64M -Xmx512M -XX:CompressedClassSpaceSize=96M"
  - export JAVA_OPTS="$JAVA_OPTS -XX:CompressedClassSpaceSize=96M"

before_script:
  - unset GEM_PATH GEM_HOME IRBRC JRUBY_OPTS
  - unset _JAVA_OPTIONS # travis/travis#8408
  - export PATH="`pwd`/bin:$PATH"
  - echo $HOME
  - echo $JAVA_OPTS
  - echo $MAVEN_OPTS

jdk:
  - openjdk8

os:
  - linux

env:
  global:
    - JAVA_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xms48M -Xmx640M -XX:InitialCodeCacheSize=40M -XX:ReservedCodeCacheSize=120M -Djava.security.egd=file:/dev/./urandom"
    - MALLOC_ARENA_MAX=2


jobs:
  include:
    - stage: test
      env: PHASE='-Ptest'
    - env: PHASE='-Prake -Dtask=test:mri:int'
    - env: PHASE='-Prake -Dtask=test:mri:fullint'
    - env: PHASE='-Prake -Dtask=test:mri:jit'
    - env: PHASE='-Prake -Dtask=test:jruby'
    - env:
      - PHASE='-Prake -Dtask=test:jruby'
        JRUBY_OPTS=-Xcompile.invokedynamic
    - env: PHASE='-Prake -Dtask=test:jruby:aot'
    - env: PHASE='-Prake -Dtask=test:jruby:fullint'
    - env: PHASE='-Prake -Dtask=test:slow_suites'
    - env: PHASE='-Prake -Dtask=spec:ji'
    - env: PHASE='-Prake -Dtask=spec:compiler'
    - env:
      - PHASE='-Prake -Dtask=spec:compiler'
        JRUBY_OPTS=-Xcompile.invokedynamic
    - env: PHASE='-Prake -Dtask=spec:ffi'
    - env: PHASE='-Prake -Dtask=spec:regression'
    - env: PHASE='-Prake -Dtask=spec:ruby:fast'
    - env: PHASE='-Prake -Dtask=spec:jruby'
    - env: PHASE='-Prake -Dtask=spec:jrubyc'
    - env: PHASE='-Prake -Dtask=spec:profiler'
    - env: PHASE='-Pdist'
    - env: PHASE='-Pjruby-jars'
    - env: PHASE='-Pmain'
    - env: PHASE='-Pcomplete'
    - env: PHASE='-Posgi'
    - env: PHASE='-Pj2ee'
    - env: PHASE='-Pjruby-jars,test -Dinvoker.test=extended'
    - env: PHASE='-Pmain,test -Dinvoker.test=extended'
    - env: PHASE='-Pjruby_complete_jar_extended -Dinvoker.skip=true'
    - env: COMMAND=test/check_versions.sh
    - env: PHASE='-Prake -Dtask=test:jruby:jit'
      jdk: openjdk9
    - env: PHASE='-Prake -Dtask=test:mri:jit'
      jdk: openjdk9
    - env: PHASE='-Prake -Dtask=spec:ruby:fast'
      jdk: openjdk9
    - env: PHASE='-Pmain'
      jdk: openjdk9
    - env: PHASE='-Pcomplete'
      jdk: openjdk9

    - stage: deploy
      script: ./mvnw deploy -Pdist --settings .travis-maven-settings.xml -DskipTests=true -B
      branches:
        only:
        - master
        - jruby-9.1

  allow_failures:
  - env: PHASE='-Prake -Dtask=test:jruby:jit'
    jdk: openjdk9
  - env: PHASE='-Prake -Dtask=test:mri:jit'
    jdk: openjdk9
  - env: PHASE='-Prake -Dtask=spec:ruby:fast'
    jdk: openjdk9

install:
  - ./mvnw $MAVEN_CLI_OPTS package -B -Dinvoker.skip -Dmaven.test.skip
script: tool/travis-script.sh

notifications:
  irc:
    channels:
      - "irc.freenode.org#jruby"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
    skip_join: true

# we are on a branch
    on_success: always
    on_failure: never

services:
  - redis-server
  - haveged

addons:
  apt:
    packages:
      - haveged